# Generated by Django 5.0.6 on 2024-06-07 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('crop_id', models.AutoField(primary_key=True, serialize=False)),
                ('crop_type', models.CharField(choices=[('Carrots', 'Carrots'), ('Potato', 'Potato'), ('Garlic', 'Garlic'), ('Eggplant', 'Eggplant'), ('Tomato', 'Tomato'), ('Squash', 'Squash'), ('Bitter Gourd', 'Bitter Gourd'), ('Cabbage', 'Cabbage'), ('Onion', 'Onion')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_acres', models.FloatField()),
                ('barangay', models.CharField(max_length=100)),
                ('city_municipality', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('nitrogen', models.FloatField(null=True)),
                ('phosphorous', models.FloatField(null=True)),
                ('potassium', models.FloatField(null=True)),
                ('ph', models.FloatField(null=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_agrosavvy.crop')),
            ],
        ),
    ]
