# Generated by Django 5.0.6 on 2024-07-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agrosavvy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_stat',
            field=models.BooleanField(default=True),
        ),
    ]
