# Generated by Django 5.0.6 on 2024-08-30 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_agrosavvy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldcropdata',
            options={'ordering': ['-planting_date']},
        ),
        migrations.AlterModelOptions(
            name='fieldsoildata',
            options={'ordering': ['-record_date']},
        ),
    ]
