# Generated by Django 5.0.6 on 2024-07-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agrosavvy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
