# Generated by Django 5.0.6 on 2024-12-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agrosavvy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
