# Generated by Django 5.0.6 on 2024-09-06 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agrosavvy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barangay',
            options={'ordering': ['brgy_name']},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.ForeignKey(blank=True, default='Male', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_agrosavvy.gender'),
        ),
    ]
