# Generated by Django 5.0.6 on 2024-11-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agrosavvy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datarsbsa',
            options={'ordering': ['-reference_number']},
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
