# Generated by Django 5.0.6 on 2024-11-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agrosavvy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
