# Generated by Django 5.0.6 on 2024-07-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agrosavvy', '0002_alter_pendinguser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
