# Generated by Django 5.0.6 on 2024-09-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_agrosavvy', '0003_useraddress_customuser_useraddress_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-approved_date']},
        ),
    ]
