# Generated by Django 5.0.6 on 2024-09-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agrosavvy', '0003_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='brgy_name',
            field=models.CharField(choices=[('Adlaon', 'Adlaon'), ('Agsungot', 'Agsungot'), ('Apas', 'Apas'), ('Babag', 'Babag'), ('Bacayan', 'Bacayan'), ('Banilad', 'Banilad'), ('Basak Pardo', 'Basak Pardo'), ('Busay', 'Busay'), ('Calamba', 'Calamba'), ('Cambinocot', 'Cambinocot'), ('Camputhaw', 'Camputhaw'), ('Capitol Site', 'Capitol Site'), ('Carreta', 'Carreta'), ('Central', 'Central'), ('Cogon Pardo', 'Cogon Pardo'), ('Cogon Ramos', 'Cogon Ramos'), ('Day-as', 'Day-as'), ('Duljo', 'Duljo'), ('Ermita', 'Ermita'), ('Guadalupe', 'Guadalupe'), ('Guba', 'Guba'), ('Hippodromo', 'Hippodromo'), ('Inayawan', 'Inayawan'), ('Kalubihan', 'Kalubihan'), ('Kalunasan', 'Kalunasan'), ('Kamagayan', 'Kamagayan'), ('Kasambagan', 'Kasambagan'), ('Kinasang-an Pardo', 'Kinasang-an Pardo'), ('Labangon', 'Labangon'), ('Lahug', 'Lahug'), ('Lorega (Lorega San Miguel)', 'Lorega (Lorega San Miguel)'), ('Lusaran', 'Lusaran'), ('Luz', 'Luz'), ('Mabini', 'Mabini'), ('Mabolo', 'Mabolo'), ('Malubog', 'Malubog'), ('Mambaling', 'Mambaling'), ('Pahina Central', 'Pahina Central'), ('Pahina San Nicolas', 'Pahina San Nicolas'), ('Pamutan', 'Pamutan'), ('Pardo', 'Pardo'), ('Pari-an', 'Pari-an'), ('Paril', 'Paril'), ('Pasil', 'Pasil'), ('Pit-os', 'Pit-os'), ('Pulangbato', 'Pulangbato'), ('Pung-ol-Sibugay', 'Pung-ol-Sibugay'), ('Punta Princesa', 'Punta Princesa'), ('Quiot Pardo', 'Quiot Pardo'), ('Sambag I', 'Sambag I'), ('Sambag II', 'Sambag II'), ('San Antonio', 'San Antonio'), ('San Jose', 'San Jose'), ('San Nicolas Central', 'San Nicolas Central'), ('San Roque (Ciudad)', 'San Roque (Ciudad)'), ('Santa Cruz', 'Santa Cruz'), ('Sapangdaku', 'Sapangdaku'), ('Sawang Calero', 'Sawang Calero'), ('Sinsin', 'Sinsin'), ('Sirao', 'Sirao'), ('Suba Poblacion (Suba San Nicolas)', 'Suba Poblacion (Suba San Nicolas)'), ('Sudlon I', 'Sudlon I'), ('Sudlon II', 'Sudlon II'), ('Tabunan', 'Tabunan'), ('Tagbao', 'Tagbao'), ('Talamban', 'Talamban'), ('Taptap', 'Taptap'), ('Tejero (Villa Gonzalo)', 'Tejero (Villa Gonzalo)'), ('Tinago', 'Tinago'), ('Tisa', 'Tisa'), ('To-ong Pardo', 'To-ong Pardo'), ('T. Padilla', 'T. Padilla'), ('Zapatera', 'Zapatera')], max_length=50),
        ),
    ]
