# Generated by Django 5.0.6 on 2024-09-05 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_agrosavvy', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='useraddress',
        ),
        migrations.RemoveField(
            model_name='pendinguser',
            name='useraddress',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
