# Generated by Django 5.0.6 on 2024-07-13 01:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agrosavvy', '0004_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
