# Generated by Django 5.0.6 on 2024-09-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agrosavvy', '0005_ai_recommendations_alter_address_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_recommendations',
            name='nitrogen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ai_recommendations',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ai_recommendations',
            name='phosphorous',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ai_recommendations',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roleuser',
            name='roleuser',
            field=models.CharField(choices=[('da_admin', 'da_admin'), ('brgy_officer', 'brgy_officer'), ('farmer', 'farmer')], max_length=20),
        ),
    ]
