# Generated by Django 5.0.6 on 2024-09-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agrosavvy', '0005_remove_customuser_useraddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fieldcropdata',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fieldsoildata',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
