# Generated by Django 5.0.6 on 2024-09-11 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agrosavvy', '0007_alter_ai_recommendations_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_recommendations',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_agrosavvy.field'),
        ),
    ]
