# Generated by Django 5.0.6 on 2024-09-11 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_agrosavvy', '0008_ai_recommendations_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai_recommendations',
            name='field',
        ),
    ]
