# Generated by Django 5.0.6 on 2024-09-11 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agrosavvy', '0009_remove_ai_recommendations_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ai_recommendations',
            old_name='basic_output',
            new_name='recommendations',
        ),
        migrations.RemoveField(
            model_name='ai_recommendations',
            name='nitrogen',
        ),
        migrations.RemoveField(
            model_name='ai_recommendations',
            name='ph',
        ),
        migrations.RemoveField(
            model_name='ai_recommendations',
            name='phosphorous',
        ),
        migrations.RemoveField(
            model_name='ai_recommendations',
            name='potassium',
        ),
        migrations.AddField(
            model_name='ai_recommendations',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_agrosavvy.field'),
        ),
        migrations.AddField(
            model_name='ai_recommendations',
            name='fieldsoildata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_agrosavvy.fieldsoildata'),
        ),
        migrations.AddField(
            model_name='ai_recommendations',
            name='recommended_crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_agrosavvy.crop'),
        ),
    ]
