# Generated by Django 5.0.6 on 2024-09-11 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_agrosavvy', '0010_rename_basic_output_ai_recommendations_recommendations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai_recommendations',
            name='recommended_crop',
        ),
    ]
